- name: Install ntp
  become: yes
  apt:
    name: ntp
    update_cache: yes
- name: Configure ntp servers
  become: yes
  lineinfile:
    path: /etc/ntp.conf
    regex: 'pool {{ item }}\..+\.pool\.ntp\.org iburst'
    line: 'pool {{ item }}.fr.pool.ntp.org iburst'
  loop:
     - 0
     - 1
     - 2
     - 3
  notify: restart ntp
