- name: Create nginx-proxy directories
  become: yes
  file:
    path: '{{item}}'
    state: directory
  loop:
    - /var/www
    - /var/www/nginx-proxy
    - /var/www/nginx-proxy/conf.d
    - /var/www/nginx-proxy/vhost.d
    - /var/www/nginx-proxy/html
    - /var/www/nginx-proxy/certs
- name: Configure nginx-proxy docker-compose.yml
  become: yes
  template:
    src: docker-compose.yml.j2
    dest: /var/www/nginx-proxy/docker-compose.yml
- name: Configure max body size to 1GB
  become: yes
  lineinfile:
    path: /var/www/nginx-proxy/conf.d/nextcloud.conf
    regex: '^client_max_body_size'
    line: 'client_max_body_size 1g;'
    create: yes
  when: install_nextcloud is defined and install_nextcloud == true
- name: Disable nginx buffering
  become: yes
  lineinfile:
    path: /var/www/nginx-proxy/conf.d/nextcloud.conf
    regex: '^proxy_request_buffering'
    line: 'proxy_request_buffering off;'
  when: install_nextcloud is defined and install_nextcloud == true
- name: Configure nginx-proxy template file
  become: yes
  get_url:
    url: https://raw.githubusercontent.com/jwilder/nginx-proxy/master/nginx.tmpl
    dest: /var/www/nginx-proxy/nginx.tmpl
- name: Create nginx-proxy Docker network
  docker_network:
    name: nginx-proxy
    ipam_config:
      - subnet: 172.18.0.0/16
- name: Run nginx-proxy Docker containers
  docker_compose:
    project_src: /var/www/nginx-proxy/
    pull: yes
    build: yes
- name: Configure weekly updates on Monday at 05:00
  cron:
    name: Update nginx-proxy Docker containers
    minute: "0"
    hour: "5"
    weekday: "1"
    job: "/usr/local/bin/docker-compose -f /var/www/nginx-proxy/docker-compose.yml pull && /usr/local/bin/docker-compose -f /var/www/nginx-proxy/docker-compose.yml up -d --build --force-recreate"
  when: auto_update is defined and auto_update == true
- name: Disable weekly updates on Monday at 05:00
  cron:
    name: Update nginx-proxy Docker containers
    state: absent
  when: auto_update is not defined or auto_update == false
