- name: "Set hostname"
  become: yes
  hostname:
    name: '{{ hostname }}'
- name: Configure /etc/hosts
  become: yes
  lineinfile:
    path: /etc/hosts
    regex: '127\.0\.1\.1'
    line: '127.0.1.1  {{ hostname }}'
- name: Configure /etc/hosts
  become: yes
  lineinfile:
    path: /etc/hosts
    regex: '127\.0\.1\.1\s+debian\.example\.com'
    state: absent
- name: Configure /etc/hosts
  become: yes
  lineinfile:
    path: /etc/hosts
    regex: '127\.0\.1\.1\s+vps\.*'
    state: absent
