---
- name: "Install web server"
  hosts: all
  tasks:
    - import_role:
        name: hostname
    - import_role:
        name: ntp
    - import_role:
        name: postfix
    - import_role:
        name: cron-apt
    - import_role:
        name: fail2ban
    - import_role:
        name: portsentry
    - import_role:
        name: docker
    - import_role:
        name: nginx
    - import_role:
        name: iptables
    - name: Configure MAILTO crontab user setting
      cron:
        name: MAILTO
        env: yes
        value: '{{ admin_email }}'
