---
- name: "Install web server"
  hosts: all
  tasks:
    - import_role:
        name: hostname
    - import_role:
        name: ntp
    - import_role:
        name: postfix
    - import_role:
        name: docker
