---
- name: "Install web server"
  hosts: all
  tasks:
    - import_role:
        name: hostname
      tags: hostname
    - import_role:
        name: ntp
    - import_role:
        name: postfix
    - import_role:
        name: cron-apt
    - import_role:
        name: fail2ban
      tags: fail2ban
    - import_role:
        name: portsentry
      tags: portsentry
    - import_role:
        name: docker
    - import_role:
        name: nginx
      tags: nginx
    - import_role:
        name: monitoring
      tags: monitoring
    - import_role:
        name: openvpn
      when: install_vpn is defined and install_vpn == true
    - import_role:
        name: smb
      when: install_vpn is defined and install_vpn == true
    - import_role:
        name: nextcloud
      tags: nextcloud
      when: install_nextcloud is defined and install_nextcloud == true
    - import_role:
        name: wordpress
      tags: wordpress
      when: wordpress_websites is defined and wordpress_websites | length > 0
    - import_role:
        name: iptables
