- name: Create website directories
  become: yes
  file:
    path: '/var/www/{{item.hostname}}'
    state: directory
  loop: '{{ wordpress_websites }}'
- name: Create wordpress directories
  become: yes
  file:
    path: '/var/www/{{item.hostname}}/wordpress'
    state: directory
    owner: '{{ ansible_user }}'
    group: '{{ ansible_user }}'
  loop: '{{ wordpress_websites }}'
- name: Create wordpress wp-content directories
  file:
    path: '/var/www/{{item.hostname}}/wordpress/wp-content'
    state: directory
  loop: '{{ wordpress_websites }}'
- name: Create wordpress wp-content/uploads directories
  file:
    path: '/var/www/{{item.hostname}}/wordpress/wp-content/uploads'
    state: directory
  loop: '{{ wordpress_websites }}'
- name: Create wordpress wp-content/themes directories
  file:
    path: '/var/www/{{item.hostname}}/wordpress/wp-content/themes'
    state: directory
  loop: '{{ wordpress_websites }}'
- name: Create wordpress wp-content/plugins directories
  file:
    path: '/var/www/{{item.hostname}}/wordpress/wp-content/plugins'
    state: directory
  loop: '{{ wordpress_websites }}'
- name: Configure wordpress compose.yml
  become: yes
  template:
    src: .env.j2
    dest: '/var/www/{{item.hostname}}/.env'
  loop: '{{ wordpress_websites }}'
- name: 'Get USER_UID'
  command: id -u
  register: USER_UID
- name: 'Set USER_UID docker argument'
  become: yes
  lineinfile:
    path: '/var/www/{{item.hostname}}/.env'
    regexp: '^USER_UID='
    line: 'USER_UID={{ USER_UID.stdout }}'
  loop: '{{ wordpress_websites }}'
  notify: reload caddy config
- name: 'Copy compose.yml file'
  become: yes
  template:
    src: 'compose.yml.j2'
    dest: '/var/www/{{item.hostname}}/compose.yml'
  loop: '{{ wordpress_websites }}'
- name : 'Copy custom.ini file'
  become: yes
  template:
    src: 'custom.ini'
    dest: '/var/www/{{item.hostname}}/wordpress/custom.ini'
  loop: '{{ wordpress_websites }}'
- name: 'Copy Dockerfile file'
  become: yes
  template:
    src: 'Dockerfile.j2'
    dest: '/var/www/{{item.hostname}}/wordpress/Dockerfile'
  loop: '{{ wordpress_websites }}'
- name: 'Create website backup directories'
  become: yes
  file:
    path: '/var/www/{{item.hostname}}/backup'
    state: directory
    owner: '{{ ansible_user }}'
    group: '{{ ansible_user }}'
  loop: '{{ wordpress_websites }}'
- name: 'Create website backup/db directories'
  become: yes
  file:
    path: '/var/www/{{item.hostname}}/backup/db'
    state: directory
    owner: '{{ ansible_user }}'
    group: '{{ ansible_user }}'
  loop: '{{ wordpress_websites }}'
- name: 'Copy website backup scripts'
  become: yes
  template:
    src: 'create_backup.sh.j2'
    dest: '/var/www/{{item.hostname}}/backup/create_backup.sh'
    mode: '0755'
  loop: '{{ wordpress_websites }}'
- name: 'Create .env.sh file for backup script'
  become: yes
  template:
    src: '.env.sh.j2'
    dest: '/var/www/{{item.hostname}}/backup/.env.sh'
    mode: '0644'
  loop: '{{ wordpress_websites }}'
- name: Run WordPress Docker containers
  community.docker.docker_compose_v2:
    project_src: "/var/www/{{item.hostname}}/"
    pull: always
    build: always
  loop: '{{ wordpress_websites }}'
- name: Update Caddyfile
  become: yes
  template:
    src: Caddyfile.j2
    dest: /var/www/caddy/sites-enabled/{{item.hostname}}
  loop: '{{ wordpress_websites }}'
  notify: reload caddy config
- meta: flush_handlers
