- name: Preconfigure postfix
  become: yes
  debconf:
    name: postfix
    question: '{{ item.question }}'
    vtype: string
    value: '{{ item.value }}'
  loop:
    - { question: 'postfix/main_mailer_type', value: 'Internet Site' }
    - { question: 'postfix/mailname', value: '{{ hostname }}' }
- name: Install postfix
  become: yes
  apt:
    name: 
      - postfix
    update_cache: yes
- name: Configure postfix mydestination
  become: yes
  lineinfile:
    path: /etc/postfix/main.cf
    regex: "^mydestination"
    line: 'mydestination ='
  notify: restart postfix
- name: Configure postfix inet_interfaces
  become: yes
  lineinfile:
    path: /etc/postfix/main.cf
    regex: "^inet_interfaces"
    line: 'inet_interfaces = loopback-only'
  notify: restart postfix
