FROM wordpress:{{ item.wordpress_version | default(wordpress_version) }}

COPY custom.ini $PHP_INI_DIR/conf.d/

ARG USER_UID

RUN groupadd -g $USER_UID {{ ansible_user }} && \
    useradd -m -u $USER_UID -g {{ ansible_user }} {{ ansible_user }}

USER {{ ansible_user }}
