- name: Upgrade all packages
  become: yes
  apt:
    upgrade: full
    autoclean: yes
    autoremove: yes
    force_apt_get: yes
    update_cache: yes
- name: Install cron-apt
  become: yes
  apt:
    name:
      - cron-apt
    update_cache: yes
- name: Set security repositories
  become: yes
  template:
    src: templates/security.sources.list.j2
    dest: /etc/apt/security.sources.list
- name: Configure APTCOMMAND
  become: yes
  lineinfile:
    path: /etc/cron-apt/config
    regex: '^APTCOMMAND='
    line: 'APTCOMMAND=/usr/bin/apt-get'
- name: Configure OPTIONS
  become: yes
  lineinfile:
    path: /etc/cron-apt/config
    regex: '^OPTIONS='
    line: 'OPTIONS="-o quiet=1 -o Dir::Etc::SourceList=/etc/apt/security.sources.list"'
- name: Configure MAILTO
  become: yes
  lineinfile:
    path: /etc/cron-apt/config
    regex: '^MAILTO='
    line: 'MAILTO="{{ admin_email }}"'
- name: Configure MAILON
  become: yes
  lineinfile:
    path: /etc/cron-apt/config
    regex: '^MAILON='
    line: 'MAILON="always"'
- name: Configure cron-apt to install updates
  become: yes
  lineinfile:
    path: /etc/cron-apt/action.d/3-download
    regex: '^dist-upgrade'
    line: 'dist-upgrade -y -o APT::Get::Show-Upgraded=true'
- name: Configure crontab to run every Monday at 03:00
  become: yes
  lineinfile:
    path: /etc/cron.d/cron-apt
    regex: '^([\*\d]\s+){5}.+/usr/sbin/cron-apt$'
    line: '0 3	* * 1	root	test -x /usr/sbin/cron-apt && /usr/sbin/cron-apt'
- name: Configure MAILTO crontab user setting
  cron:
    name: MAILTO
    env: yes
    value: '{{ admin_email }}'
