- name: Create nextcloud directories
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ nextcloud_dir }}"
    - "{{ nextcloud_dir }}/web"
    - "{{ nextcloud_dir }}/nextcloud"
- name: Copy configuration files
  copy  :
    src: '{{item}}'
    dest: '{{ nextcloud_dir }}/{{item}}'
  loop:
    - nextcloud/Dockerfile
    - nextcloud/supervisord.conf
    - web/Dockerfile
    - web/nginx.conf
- name: Copy docker-compose.yml
  template:
    src: docker-compose.yml.j2
    dest: "{{ nextcloud_dir }}/docker-compose.yml"
- name: Run NextCloud Docker containers
  community.docker.docker_compose:
    project_src: "{{ nextcloud_dir }}/"
    build: yes
- name: Configure weekly updates on Monday at 06:00
  cron:
    name: Update NextCloud Docker containers
    minute: "0"
    hour: "6"
    weekday: "1"
    job: "/usr/local/bin/docker-compose -f {{ nextcloud_dir }}/docker-compose.yml pull && /usr/local/bin/docker-compose -f {{ nextcloud_dir }}/docker-compose.yml up -d --build --force-recreate"
  when: auto_update is defined and auto_update == true
- name: Disable weekly updates on Monday at 06:00
  cron:
    name: Update NextCloud Docker containers
    state: absent
  when: auto_update is not defined or auto_update == false
