- name: Create monitoring directories
  become: yes
  file:
    path: '{{item}}'
    state: directory
  loop:
    - /var/www
    - /var/www/monitoring
    - /var/www/monitoring/prometheus
- name: Configure monitoring docker-compose.yml
  become: yes
  template:
    src: docker-compose.yml.j2
    dest: /var/www/monitoring/docker-compose.yml
- name: Configure prometheus.yml
  become: yes
  template:
    src: prometheus.yml.j2
    dest: /var/www/monitoring/prometheus/prometheus.yml
- name: Create monitoring Docker network
  docker_network:
    name: monitoring
- name: Run monitoring Docker containers
  docker_service:
    project_src: /var/www/monitoring/
- name: Configure weekly updates on Monday at 05:00
  cron:
    name: Update montoring Docker containers
    minute: "0"
    hour: "5"
    weekday: "1"
    job: "/usr/local/bin/docker-compose -f /var/www/monitoring/docker-compose.yml pull && /usr/local/bin/docker-compose -f /var/www/monitoring/docker-compose.yml up -d --build"