- name: Install portsentry
  become: yes
  apt:
    name:
      - portsentry
    update_cache: yes
- name: Turn off portsentry TCP and UDP blocking
  become: yes
  lineinfile:
    path: /etc/portsentry/portsentry.conf
    regex: '^{{ item }}="\d"$'
    line: '{{ item }}="0"'
  loop:
    - BLOCK_TCP
    - BLOCK_UDP
  notify: restart portsentry
- name: Turn off portsentry kill blocking
  become: yes
  lineinfile:
    path: /etc/portsentry/portsentry.conf
    regex: '^KILL_ROUTE='
    line: '#\0'
  notify: restart portsentry
- name: Configure Portsentry to scan TCP ports from 1 to 1024
  become: yes
  ansible.builtin.lineinfile:
    path: /etc/portsentry/portsentry.conf
    regexp: '^ADVANCED_PORTS_TCP='
    line: 'ADVANCED_PORTS_TCP="1024"'
  notify: restart portsentry
- name : Configure Portsentry to scan UDP ports from 1 to 1024
  become: yes
  ansible.builtin.lineinfile:
    path: /etc/portsentry/portsentry.conf
    regexp: '^ADVANCED_PORTS_UDP='
    line: 'ADVANCED_PORTS_UDP="1024"'
  notify: restart portsentry
- name: Configure to ignore TCP ports 80 and 443
  become: yes
  lineinfile:
    path: /etc/portsentry/portsentry.conf
    regex: '^ADVANCED_EXCLUDE_TCP='
    line: 'ADVANCED_EXCLUDE_TCP="80,443"'
  notify: restart portsentry
- name: Configure TCP and UDP to advanced mode
  become: yes
  lineinfile:
    path: /etc/default/portsentry
    regex: '^{{ item.mode }}='
    line: '{{ item.mode }}="{{ item.value }}"'
  loop:
    - { mode: 'TCP_MODE', value: 'atcp' }
    - { mode: 'UDP_MODE', value: 'audp' }
  notify: restart portsentry
- name: Create fail2ban filter for portsentry
  become: yes
  copy:
    dest: /etc/fail2ban/filter.d/portsentry.conf
    src: 'portsentry.conf'
  notify: restart fail2ban
- name: Config fail2ban jail for portsentry
  become: yes
  copy:
    dest: /etc/fail2ban/jail.d/portsentry.conf
    src: 'fail2ban.conf'
  notify: restart fail2ban
- meta: flush_handlers
