- name: Install portsentry
  become: yes
  apt:
    name:
      - portsentry
    update_cache: yes
- name: Configure to block TCP and UDP scans
  become: yes
  lineinfile:
    path: /etc/portsentry/portsentry.conf
    regex: '^{{ item }}="\d"$'
    line: '{{ item }}="1"'
  loop:
    - BLOCK_TCP
    - BLOCK_UDP
  notify: restart portsentry
- name: Configure TCP and UDP to advanced mode
  become: yes
  lineinfile:
    path: /etc/default/portsentry
    regex: '^{{ item.mode }}='
    line: '{{ item.mode }}="{{ item.value }}"'
  loop:
    - { mode: 'TCP_MODE', value: 'atcp' }
    - { mode: 'UDP_MODE', value: 'audp' }
  notify: restart portsentry
- meta: flush_handlers
