version: "3.8"
services:
    openvpn:
        image: kylemanna/openvpn
        container_name: openvpn
        restart: always
        volumes:
            - openvpn-data:/etc/openvpn
        ports:
            - "1194:1194/udp"
        cap_add:
            - NET_ADMIN

volumes:
    openvpn-data:
        external: true
        name: openvpn-data

networks:
    default:
        external:
            name: openvpn
