- name: Install fail2ban
  become: yes
  apt:
    name: 
      - fail2ban
    update_cache: yes
- name: Configure fail2ban
  become: yes
  template:
    src: jail.local.j2
    dest: /etc/fail2ban/jail.local
  notify: restart fail2ban
