- name: "Install docker required packages"
  become: yes
  apt:
    name:
      - ca-certificates
      - curl
      - gnupg
    update_cache: yes
- name: "Add Docker's official GPG key"
  become: yes
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    keyring: /etc/apt/trusted.gpg.d/docker.gpg
- name: Get architecture
  command: dpkg --print-architecture
  register: dpkg_architecture
- name: "Add Docker's repository"
  become: yes
  apt_repository:
    repo: "deb [arch={{ dpkg_architecture.stdout }} signed-by=/etc/apt/trusted.gpg.d/docker.gpg] https://download.docker.com/linux/debian {{ ansible_facts['distribution_release'] }} stable"
- name: "Install Docker"
  become: yes
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    update_cache: yes
- name: Create docker group
  become: yes
  group:
    name: docker
- name: Add {{ ansible_user }} to docker group
  become: yes
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes
- meta: reset_connection
- name: Install pip
  become: yes
  apt:
    name:
      - python3-pip
    update_cache: yes
- name: Install Docker and Docker Compose SDKs for Python
  pip:
    name:
      - docker
      - docker-compose<2.0.0
    state: latest
