- name: "Install docker required packages"
  become: yes
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
    update_cache: yes
- name: "Add Docker's official GPG key"
  become: yes
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
- name: "Add Docker's repository"
  become: yes
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/debian {{ ansible_facts['distribution_release'] }} stable"
- name: "Install Docker"
  become: yes
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    update_cache: yes
- name: Create docker group
  become: yes
  group:
    name: docker
- name: Add {{ ansible_user }} to docker group
  become: yes
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes
- meta: flush_handlers
- meta: reset_connection
- name: Install Docker Compose
  become: yes
  get_url:
    url: https://github.com/docker/compose/releases/download/{{ docker_composer_version }}/docker-compose-{{ ansible_facts['system'] }}-{{ ansible_facts['userspace_architecture'] }}
    dest: /usr/local/bin/docker-compose
    mode: 0755
# - name: Install pip
#   become: yes
#   apt:
#     name:
#       - python-pip
#       - python-setuptools
#     update_cache: yes
- name: Install pip3
  become: yes
  apt:
    name:
      - python3-pip
    update_cache: yes
  when: ansible_python_interpreter is defined and ansible_python_interpreter == "/usr/bin/python3" or ansible_facts['distribution'] == "Debian" and ansible_facts['distribution_version'] >= 10
- name: Install Docker and Docker Compose SDKs for Python
  pip:
    name:
      - docker
      - docker-compose
    state: latest
