[Definition]
failregex = portsentry\[\d+\]: attackalert: TCP.* scan from host: <HOST>/\S+ to TCP port: \d+
            portsentry\[\d+\]: attackalert: Host: <HOST>/\S+ is already blocked
ignoreregex =
