- name: Create openvpn directory
  file:
    path: ~/openvpn
    state: directory
- name: Install expect
  become: yes
  apt:
    name: expect
    update_cache: yes
- name: Copy docker-compose.yml
  copy:
    src: docker-compose.yml
    dest: ~/openvpn/docker-compose.yml
- name: Create openvpn Docker network
  docker_network:
    name: openvpn
- name: Copy configuration script
  template:
    src: configure-vpn.sh.j2
    dest: ~/openvpn/configure-vpn.sh
    mode: 0744
  register: configuration_script
- name: Copy parameters file
  template:
    src: script-configure.exp.j2
    dest: ~/openvpn/script-configure.exp
    mode: 0744
  when: configuration_script.changed
- name: Configure OpenVPN
  command: ~/openvpn/script-configure.exp
  when: configuration_script.changed
- name: Copy client certificate script
  template:
    src: client-certificate.sh.j2
    dest: ~/openvpn/client-certificate.sh
    mode: 0744
  register: certificate_script
- name: Copy parameter file
  template:
    src: script-client.exp.j2
    dest: ~/openvpn/script-client.exp
    mode: 0744
  when: certificate_script.changed
- name: Generate client certificate
  command: ~/openvpn/script-client.exp {{ item.name }} {{ item.passphrase }}
  loop: "{{ vpn_client_certificates }}"
  when: certificate_script.changed
- name: Configure fallback VPN using TCP on port 80
  lineinfile:
    path: ~/openvpn/{{ item.name }}.ovpn
    insertafter: '^remote {{ hostname }} 1194 udp'
    regexp: '^remote {{ hostname }} 80 tcp'
    line: 'remote {{ hostname }} 80 tcp'
  loop: "{{ vpn_client_certificates }}"
  when: certificate_script.changed
- name: Fetch client certificate
  fetch:
    src: ~/openvpn/{{ item.name }}.ovpn
    dest: "{{ inventory_dir }}/"
    flat: yes
  loop: "{{ vpn_client_certificates }}"
  when: certificate_script.changed
- name: Remove client .ovpn files
  file:
    path: ~/openvpn/{{ item.name }}.ovpn
    state: absent
  loop: "{{ vpn_client_certificates }}"
- name: Remove parameters files
  file:
    path: ~/openvpn/{{ item }}.exp
    state: absent
  loop:
    - script-configure
    - script-client
- name: Run OpenVPN Docker containers
  docker_compose:
    project_src: ~/openvpn/
- name: Configure weekly updates on Monday at 06:00
  cron:
    name: Update openvpn Docker containers
    minute: "0"
    hour: "6"
    weekday: "1"
    job: "/usr/local/bin/docker-compose -f /home/{{ ansible_user }}/openvpn/docker-compose.yml pull && /usr/local/bin/docker-compose -f /home/{{ ansible_user }}/openvpn/docker-compose.yml up -d --build"
